apiVersion: apps/v1
kind: Deployment  
metadata:
  name: frontend-deployment
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 146578669895.dkr.ecr.ap-south-1.amazonaws.com/frontend:29
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: "http://amanpathakdevops.study/api/tasks"
          resources:
            requests:
              memory: "256Mi"
              cpu: "256m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:  
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
