apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: webapp
type: Opaque
stringData:
  username: YWRtaW4K  # base64 encoded 'admin'
  password: cGFzc3dvcmQxMjMK  # base64 encoded 'password123'